version: '3.8'
services:

  redis:
    container_name: redis-container
    hostname: redis
    image: redis:7.2
    ports:
      - 6379:6379

  celery:
    container_name: celery-container
    
    image: celery-image:1.2.1
    volumes: 
      - ../logs:/app/logs
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 